import datetime
from typing import Dict

import pytest
from ya_market.models.proposal import Proposal as yaProposal


@pytest.fixture
def yagna_proposal():
    def _yagna_proposal(properties: Dict = {}):
        return yaProposal(
            proposal_id="R-8bee6cba3e99059ee2a9a355c7f9d502f2ee836cecd00d98ebac87cc88b9fc4f",
            issuer_id="0xf97cdecb935fc970ed1bd3da6eacc7a325e582dc",
            state="Initial",
            timestamp=datetime.datetime.utcnow(),
            constraints="(&\n"
            "  (golem.srv.comp.expiration>4843951180715)\n"
            "  (golem.node.debug.subnet=public)\n"
            ")",
            properties={
                "golem.activity.caps.transfer.protocol": ["http", "https", "gftp"],
                "golem.com.payment.debit-notes.accept-timeout?": 240,
                "golem.com.pricing.model": "linear",
                "golem.com.pricing.model.linear.coeffs": [5e-05, 0.0001, 0.0],
                "golem.com.scheme": "payu",
                "golem.com.scheme.payu.debit-note.interval-sec?": 120,
                "golem.com.scheme.payu.payment-timeout-sec?": 120,
                "golem.com.usage.vector": ["golem.usage.duration_sec", "golem.usage.cpu_sec"],
                "golem.inf.cpu.architecture": "x86_64",
                "golem.inf.cpu.brand": "Intel(R) Core(TM) i7-8700 CPU @ " "3.20GHz",
                "golem.inf.cpu.capabilities": [
                    "sse3",
                    "pclmulqdq",
                    "dtes64",
                    "monitor",
                    "dscpl",
                    "vmx",
                    "smx",
                    "eist",
                    "tm2",
                    "ssse3",
                    "fma",
                    "cmpxchg16b",
                    "pdcm",
                    "pcid",
                    "sse41",
                    "sse42",
                    "x2apic",
                    "movbe",
                    "popcnt",
                    "tsc_deadline",
                    "aesni",
                    "xsave",
                    "osxsave",
                    "avx",
                    "f16c",
                    "rdrand",
                    "fpu",
                    "vme",
                    "de",
                    "pse",
                    "tsc",
                    "msr",
                    "pae",
                    "mce",
                    "cx8",
                    "apic",
                    "sep",
                    "mtrr",
                    "pge",
                    "mca",
                    "cmov",
                    "pat",
                    "pse36",
                    "clfsh",
                    "ds",
                    "acpi",
                    "mmx",
                    "fxsr",
                    "sse",
                    "sse2",
                    "ss",
                    "htt",
                    "tm",
                    "pbe",
                    "fsgsbase",
                    "adjust_msr",
                    "bmi1",
                    "hle",
                    "avx2",
                    "smep",
                    "bmi2",
                    "rep_movsb_stosb",
                    "invpcid",
                    "rtm",
                    "deprecate_fpu_cs_ds",
                    "mpx",
                    "rdseed",
                    "adx",
                    "smap",
                    "clflushopt",
                    "processor_trace",
                    "sgx",
                    "sgx_lc",
                ],
                "golem.inf.cpu.cores": 6,
                "golem.inf.cpu.model": "Stepping 10 Family 6 Model 302",
                "golem.inf.cpu.threads": 1,
                "golem.inf.cpu.vendor": "GenuineIntel",
                "golem.inf.mem.gib": 4.0,
                "golem.inf.storage.gib": 40.0,
                "golem.node.debug.subnet": "public",
                "golem.node.id.name": "golem2005_2.h",
                "golem.node.net.is-public": False,
                "golem.runtime.capabilities": [
                    "inet",
                    "vpn",
                    "manifest-support",
                    "start-entrypoint",
                ],
                "golem.runtime.name": "vm",
                "golem.runtime.version": "0.3.0",
                "golem.srv.caps.multi-activity": True,
                "golem.srv.caps.payload-manifest": True,
                **properties,
            },
        )

    return _yagna_proposal
