name: Integration tests
on:
  push:
    branches:
      - main
      - b0.*
  pull_request:
    branches:
      - main
      - b0.*

jobs:
  tests-integration:
    name: Run checks
    runs-on: [goth, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Install dependencies
        run: |
          poetry env use python3.8
          poetry install

      - name: Disconnect Docker containers from default network
        continue-on-error: true
        # related to this issue: https://github.com/moby/moby/issues/23302
        run: |
          docker network inspect docker_default
          sudo apt-get install -y jq
          docker network inspect docker_default | jq ".[0].Containers | map(.Name)[]" | tee /dev/stderr | xargs --max-args 1 -- docker network disconnect -f docker_default

      - name: Remove Docker containers
        continue-on-error: true
        run: docker rm --force $(docker ps -a -q)

      - name: Restart Docker daemon
        # related to this issue: https://github.com/moby/moby/issues/23302
        run: sudo systemctl restart docker

      - name: Log in to GitHub Docker repository
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{github.actor}} --password-stdin
        
      - name: Setup goth golem network
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run ./tests/integration/run-goth.sh

      - name: Run tests
        run: poetry run ./tests/integration/run-tests.sh

      - name: Remove Docker containers
        if: always()
        continue-on-error: true
        run: docker rm --force $(docker ps -a -q)

      - name: Stop goth network
        if: always()
        continue-on-error: true
        run: kill $(ps -aux | grep "[g]oth start" | awk '{print $2}')
