name: Integration tests nightly
on:
  schedule:
    # run this workflow every day at 2:00 AM UTC
    - cron: '0 2 * * *'

jobs:
  tests-integration:
    name: Run checks
    runs-on: [goth, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests action
        uses: './.github/actions/integration-tests-goth'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Discord notification on failure
        uses: Ilshidur/action-discord@0.3.2
        if: ${{ failure() }} || ${{ cancelled() }}
        env:
          BRANCH_NAME: main
          DISCORD_AVATAR: https://i.imgur.com/EOX16Mx.jpg
          DISCORD_USERNAME: "Goth night watch"
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          # <@&717623005911580713> = @sdk-integrations
          args: "<@&717623005911580713> Goth nightly run failed for `{{ REPO_NAME }}` on branch `{{ BRANCH_NAME }}`! <{{ WORKFLOW_URL }}>"
