name: Continuous integration
on:
  push:
    branches:
      - main
      - b0.*
  pull_request:
    branches:
      - main
      - b0.*

jobs:
  test:
    name: Run checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest # requires https://github.com/golemfactory/golem-core-python/issues/79
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.5.0

      - run: poetry install

      - run: poetry run poe tests_unit
      - run: poetry run poe checks
      - run: poetry run poe sphinx -W
